server:
  port: 9999

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/basic
    username: root
    password: qwerty0922
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create-drop